/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.DanhSachPhieuKiemTien_DAO;
import entity.BangKiemTien;
import entity.NhanVien;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import raven.toast.Notifications;
import utilities.CashCountSheetPrinter;

/**
 *
 * @author HÀ NHƯ
 */
public class DanhSachPhieuKiemTien_GUI extends javax.swing.JPanel {

    private DefaultTableModel model;
    private DanhSachPhieuKiemTien_DAO danhSachPhieuKiemTien_DAO = new DanhSachPhieuKiemTien_DAO();

    /**
     * Creates new form DanhSachPhieuKiemTien_GUI
     */
    public DanhSachPhieuKiemTien_GUI() {
        initComponents();
        initTableModel();
        alterTable();
        renderCustomerTable(danhSachPhieuKiemTien_DAO.getAll());
    }

    public void alterTable() {
        DefaultTableCellRenderer rightAlign = new DefaultTableCellRenderer();
        rightAlign.setHorizontalAlignment(JLabel.RIGHT);

////        Align
        tbl_bangKiemTien.getColumnModel().getColumn(4).setCellRenderer(rightAlign);
        tbl_bangKiemTien.getColumnModel().getColumn(5).setCellRenderer(rightAlign);

    }

    public void renderCustomerTable(ArrayList<BangKiemTien> list) {
        model.setRowCount(0);
        for (BangKiemTien bangKiemTien : list) {
            String id = bangKiemTien.getMaBangKiemTien();
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            NhanVien nv1 = bangKiemTien.getListChiTietBangKiemTien().get(0).getNhanVien();
            NhanVien nv2 = bangKiemTien.getListChiTietBangKiemTien().get(1).getNhanVien();

            Date ngayBatDau = bangKiemTien.getNgayBatDau();
            double tongTien = bangKiemTien.getTongTien();
            double chenhLech = bangKiemTien.getChenhLech();

            Object[] row = new Object[]{id, nv1.getMaNhanVien(), nv2.getMaNhanVien(), formatter.format(ngayBatDau), utilities.FormatNumber.toVND(tongTien), utilities.FormatNumber.toVND(chenhLech)};
            model.addRow(row);
        }
    }

    public void initTableModel() {
        // Products
        model = new DefaultTableModel(new String[]{"Mã", "Người kiểm", "Đồng kiểm", "Thời điểm lập", "Tổng", "Chênh lệch"
        }, 0);
        tbl_bangKiemTien.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_loc = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        txt_maNhanVienDongKiem = new javax.swing.JTextField();
        txt_maNhanVien = new javax.swing.JTextField();
        jChooseDateEnd = new com.toedter.calendar.JDateChooser();
        jChoose_DateStart = new com.toedter.calendar.JDateChooser();
        jcbChenhLech = new javax.swing.JComboBox<>();
        jcbTong = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bangKiemTien = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nhân viên kiểm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jLabel2.setText("Từ ngày:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 70, 33));

        jLabel3.setText("Nhân viên đồng kiểm");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 45, 160, 33));

        jLabel4.setText("Đến ngày:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 60, 33));

        jLabel5.setText("Tổng từ:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 90, 33));

        jLabel6.setText("Chênh lệch:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 80, 33));

        btn_loc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/funnel.png"))); // NOI18N
        btn_loc.setText("Lọc");
        btn_loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locActionPerformed(evt);
            }
        });
        jPanel1.add(btn_loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 86, 30));

        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/refresh.png"))); // NOI18N
        btn_reset.setText("Reset");
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, 30));

        txt_maNhanVienDongKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNhanVienDongKiemActionPerformed(evt);
            }
        });
        jPanel1.add(txt_maNhanVienDongKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 50, 200, 30));
        jPanel1.add(txt_maNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 11, 202, 30));
        jPanel1.add(jChooseDateEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 210, 30));
        jPanel1.add(jChoose_DateStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 210, 30));

        jcbChenhLech.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbChenhLech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Dưới 1 triệu", "Từ 1 triệu - 2 triệu", "Từ 2 triệu - 5 triệu", "Trên 5 triệu" }));
        jPanel1.add(jcbChenhLech, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 210, 30));

        jcbTong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbTong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Dưới 1 triệu", "Từ 1 triệu - 2 triệu", "Từ 2 triệu - 5 triệu", "Trên 5 triệu" }));
        jPanel1.add(jcbTong, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 210, 30));

        tbl_bangKiemTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Người kiểm", "Đồng kiểm", "Thời điểm lập", "Tổng", "Chênh lệch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_bangKiemTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangKiemTienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bangKiemTien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maNhanVienDongKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNhanVienDongKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNhanVienDongKiemActionPerformed

    private void tbl_bangKiemTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangKiemTienMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbl_bangKiemTien.getSelectedRow();

        // Kiểm tra xem có dòng nào được chọn không
        if (selectedRow != -1) {
            // Lấy giá trị ô đầu tiên trong dòng được chọn
            Object firstCellValue = tbl_bangKiemTien.getValueAt(selectedRow, 0);

            // In giá trị ô đầu tiên ra console hoặc thực hiện các thao tác khác với giá trị này
            CashCountSheetPrinter printer = new CashCountSheetPrinter(danhSachPhieuKiemTien_DAO.getOne((String) firstCellValue));
            printer.generatePDF();
            CashCountSheetPrinter.PrintStatus status = printer.printFile();
            if (status == CashCountSheetPrinter.PrintStatus.NOT_FOUND_FILE) {
                Notifications.getInstance().show(Notifications.Type.ERROR, "Lỗi không thể in hóa đơn: Không tìm thấy file");
            } else if (status == CashCountSheetPrinter.PrintStatus.NOT_FOUND_PRINTER) {
                Notifications.getInstance().show(Notifications.Type.ERROR, "Lỗi không thể in hóa đơn: Không tìm thấy máy in");
            }
        }
    }//GEN-LAST:event_tbl_bangKiemTienMouseClicked

    private void btn_locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locActionPerformed
        String maNhanVien1 = txt_maNhanVien.getText();
        String maNhanVien2 = txt_maNhanVienDongKiem.getText();
        Date start = jChoose_DateStart.getDate();
        Date end = jChooseDateEnd.getDate();
        double startValueTong = 0;
        double endValueTong = 0;
        double startValueChenhLech = 0;
        double endValueChenhLech = 0;
        int typeTong = 0;
        int typeChenhLech = 0;
        if (jcbTong.getSelectedIndex() == 1) {
            typeTong = 1;
            endValueTong = 1000000;
        } else if (jcbTong.getSelectedIndex() == 2) {
            typeTong = 2;
            startValueTong = 1000000;
            endValueTong = 2000000;
        } else if (jcbTong.getSelectedIndex() == 3) {
            typeTong = 2;
            startValueTong = 2000000;
            endValueTong = 5000000;
        } else if (jcbTong.getSelectedIndex() == 4) {
            typeTong = 3;
            startValueTong = 5000000;
        }

        if (jcbChenhLech.getSelectedIndex() == 1) {
            typeChenhLech = 1;
            endValueChenhLech = 1000000;
        } else if (jcbChenhLech.getSelectedIndex() == 2) {
            typeChenhLech = 2;
            startValueChenhLech = 1000000;
            endValueChenhLech = 2000000;
        } else if (jcbChenhLech.getSelectedIndex() == 3) {
            typeChenhLech = 2;
            startValueChenhLech = 2000000;
            endValueChenhLech = 5000000;
        } else if (jcbChenhLech.getSelectedIndex() == 4) {
            typeChenhLech = 3;
            startValueChenhLech = 5000000;
        }

    }//GEN-LAST:event_btn_locActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_loc;
    private javax.swing.JButton btn_reset;
    private com.toedter.calendar.JDateChooser jChooseDateEnd;
    private com.toedter.calendar.JDateChooser jChoose_DateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbChenhLech;
    private javax.swing.JComboBox<String> jcbTong;
    private javax.swing.JTable tbl_bangKiemTien;
    private javax.swing.JTextField txt_maNhanVien;
    private javax.swing.JTextField txt_maNhanVienDongKiem;
    // End of variables declaration//GEN-END:variables
}
