/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.DanhSachPhieuKiemTien_DAO;
import entity.BangKiemTien;
import entity.NhanVien;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import raven.toast.Notifications;
import utilities.CashCountSheetPrinter;

/**
 *
 * @author HÀ NHƯ
 */
public class DanhSachPhieuKiemTien_GUI extends javax.swing.JPanel {

    private DefaultTableModel model;
    private DanhSachPhieuKiemTien_DAO danhSachPhieuKiemTien_DAO = new DanhSachPhieuKiemTien_DAO();

    /**
     * Creates new form DanhSachPhieuKiemTien_GUI
     */
    public DanhSachPhieuKiemTien_GUI() {
        initComponents();
        initTableModel();
        alterTable();
        renderCustomerTable(danhSachPhieuKiemTien_DAO.getAll());
    }

    public void alterTable() {
        DefaultTableCellRenderer rightAlign = new DefaultTableCellRenderer();
        rightAlign.setHorizontalAlignment(JLabel.RIGHT);

////        Align
        tbl_bangKiemTien.getColumnModel().getColumn(4).setCellRenderer(rightAlign);
        tbl_bangKiemTien.getColumnModel().getColumn(5).setCellRenderer(rightAlign);

    }

    public void renderCustomerTable(ArrayList<BangKiemTien> list) {
        model.setRowCount(0);
        for (BangKiemTien bangKiemTien : list) {
            String id = bangKiemTien.getMaBangKiemTien();
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            NhanVien nv1 = bangKiemTien.getListChiTietBangKiemTien().get(0).getNhanVien();
            NhanVien nv2 = bangKiemTien.getListChiTietBangKiemTien().get(1).getNhanVien();

            Date ngayBatDau = bangKiemTien.getNgayBatDau();
            double tongTien = bangKiemTien.getTongTien();
            double chenhLech = bangKiemTien.getChenhLech();

            Object[] row = new Object[]{id, nv1.getMaNhanVien(), nv2.getMaNhanVien(), formatter.format(ngayBatDau), utilities.FormatNumber.toVND(tongTien), utilities.FormatNumber.toVND(chenhLech)};
            model.addRow(row);
        }
    }

    public void initTableModel() {
        // Products
        model = new DefaultTableModel(new String[]{"Mã", "Người kiểm", "Đồng kiểm", "Thời điểm lập", "Tổng", "Chênh lệch"
        }, 0);
        tbl_bangKiemTien.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_loc = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        txt_maNhanVienDongKiem = new javax.swing.JTextField();
        txt_maNhanVien = new javax.swing.JTextField();
        jChooseDateEnd = new com.toedter.calendar.JDateChooser();
        jChoose_DateStart = new com.toedter.calendar.JDateChooser();
        jcbChenhLech = new javax.swing.JComboBox<>();
        jcbTong = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bangKiemTien = new javax.swing.JTable();

        jLabel1.setText("Nhân viên kiểm");

        jLabel2.setText("Từ ngày:");

        jLabel3.setText("Nhân viên đồng kiểm");

        jLabel4.setText("Đến ngày:");

        jLabel5.setText("Tổng từ:");

        jLabel6.setText("Chênh lệch:");

        btn_loc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/funnel.png"))); // NOI18N
        btn_loc.setText("Lọc");
        btn_loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locActionPerformed(evt);
            }
        });

        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/refresh.png"))); // NOI18N
        btn_reset.setText("Reset");

        txt_maNhanVienDongKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNhanVienDongKiemActionPerformed(evt);
            }
        });

        jcbChenhLech.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbChenhLech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Dưới 1 triệu", "Từ 1 triệu - 2 triệu", "Từ 2 triệu - 5 triệu", "Trên 5 triệu" }));

        jcbTong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbTong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Dưới 1 triệu", "Từ 1 triệu - 2 triệu", "Từ 2 triệu - 5 triệu", "Trên 5 triệu" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_maNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jChoose_DateStart, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jcbTong, 0, 210, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addGap(200, 200, 200)))
                        .addGap(20, 20, 20)
                        .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(txt_maNhanVienDongKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addGap(174, 174, 174)))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jChooseDateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jcbChenhLech, 0, 210, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_loc, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jChoose_DateStart, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbTong, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txt_maNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_maNhanVienDongKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(jChooseDateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(jcbChenhLech, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(btn_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(3, 3, 3))))))
        );

        tbl_bangKiemTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Người kiểm", "Đồng kiểm", "Thời điểm lập", "Tổng", "Chênh lệch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_bangKiemTien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangKiemTienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bangKiemTien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_maNhanVienDongKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNhanVienDongKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNhanVienDongKiemActionPerformed

    private void tbl_bangKiemTienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangKiemTienMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbl_bangKiemTien.getSelectedRow();

        // Kiểm tra xem có dòng nào được chọn không
        if (selectedRow != -1) {
            // Lấy giá trị ô đầu tiên trong dòng được chọn
            Object firstCellValue = tbl_bangKiemTien.getValueAt(selectedRow, 0);

            // In giá trị ô đầu tiên ra console hoặc thực hiện các thao tác khác với giá trị này
            CashCountSheetPrinter printer = new CashCountSheetPrinter(danhSachPhieuKiemTien_DAO.getOne((String) firstCellValue));
            printer.generatePDF();
            CashCountSheetPrinter.PrintStatus status = printer.printFile();
            if (status == CashCountSheetPrinter.PrintStatus.NOT_FOUND_FILE) {
                Notifications.getInstance().show(Notifications.Type.ERROR, "Lỗi không thể in hóa đơn: Không tìm thấy file");
            } else if (status == CashCountSheetPrinter.PrintStatus.NOT_FOUND_PRINTER) {
                Notifications.getInstance().show(Notifications.Type.ERROR, "Lỗi không thể in hóa đơn: Không tìm thấy máy in");
            }
        }
    }//GEN-LAST:event_tbl_bangKiemTienMouseClicked

    private void btn_locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locActionPerformed
        String maNhanVien1 = txt_maNhanVien.getText();
        String maNhanVien2 = txt_maNhanVienDongKiem.getText();
        Date start = jChoose_DateStart.getDate();
        Date end = jChooseDateEnd.getDate();
        double startValueTong = 0;
        double endValueTong = 0;
        double startValueChenhLech = 0;
        double endValueChenhLech = 0;
        int typeTong = 0;
        int typeChenhLech = 0;
        if (jcbTong.getSelectedIndex() == 1) {
            typeTong = 1;
            endValueTong = 1000000;
        } else if (jcbTong.getSelectedIndex() == 2) {
            typeTong = 2;
            startValueTong = 1000000;
            endValueTong = 2000000;
        } else if (jcbTong.getSelectedIndex() == 3) {
            typeTong = 2;
            startValueTong = 2000000;
            endValueTong = 5000000;
        } else if (jcbTong.getSelectedIndex() == 4) {
            typeTong = 3;
            startValueTong = 5000000;
        }

        if (jcbChenhLech.getSelectedIndex() == 1) {
            typeChenhLech = 1;
            endValueChenhLech = 1000000;
        } else if (jcbChenhLech.getSelectedIndex() == 2) {
            typeChenhLech = 2;
            startValueChenhLech = 1000000;
            endValueChenhLech = 2000000;
        } else if (jcbChenhLech.getSelectedIndex() == 3) {
            typeChenhLech = 2;
            startValueChenhLech = 2000000;
            endValueChenhLech = 5000000;
        } else if (jcbChenhLech.getSelectedIndex() == 4) {
            typeChenhLech = 3;
            startValueChenhLech = 5000000;
        }

    }//GEN-LAST:event_btn_locActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_loc;
    private javax.swing.JButton btn_reset;
    private com.toedter.calendar.JDateChooser jChooseDateEnd;
    private com.toedter.calendar.JDateChooser jChoose_DateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbChenhLech;
    private javax.swing.JComboBox<String> jcbTong;
    private javax.swing.JTable tbl_bangKiemTien;
    private javax.swing.JTextField txt_maNhanVien;
    private javax.swing.JTextField txt_maNhanVienDongKiem;
    // End of variables declaration//GEN-END:variables
}
