package gui.QuenMatKhau.textfield;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author RAVEN
 */
public class Main extends javax.swing.JFrame {

    private PasswordField f1;

    public Main() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));  // Đặt màu nền cho JFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Tạo JPanel và thiết lập layout null để dễ dàng đặt vị trí các thành phần
        JPanel panel = new JPanel();
        panel.setLayout(null); // Layout null cho phép đặt vị trí theo tọa độ

        // Tạo RoundedButton và thiết lập vị trí
        RoundedButton button = new RoundedButton("Click Me");
        button.setBounds(100, 100, 200, 50); // Vị trí và kích thước của nút
        panel.add(button); // Thêm RoundedButton vào panel

        // Thêm panel vào JFrame
        getContentPane().add(panel);

        pack();
        setLocationRelativeTo(null);  // Đặt JFrame ở giữa màn hình
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
