/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.QuenMatKhau;

import com.itextpdf.text.log.Logger;
import dao.TaiKhoan_DAO;
import gui.LoginForm;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import message.Notification;
import org.apache.logging.log4j.Level;
import raven.toast.Notifications;
import utilities.hashPassowrd;
import utilities.regax_Nhan;

/**
 *
 * @author Lenovo
 */
public class DoiMatKhau extends javax.swing.JPanel {

    /**
     * Creates new form DoiMatKhau
     */
    private LoginForm loginForm;
    private ResetListener resetListener;
    private TaiKhoan_DAO tk_dao = new TaiKhoan_DAO();
    private String tenTK;
    private regax_Nhan regax = new regax_Nhan();
    private hashPassowrd hashpwd = new hashPassowrd();

    public DoiMatKhau(String ten, LoginForm loginForm1) {
        tenTK = ten;
        loginForm=loginForm1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lb_thongBao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_mk1 = new gui.QuenMatKhau.textfield.TextField();
        tf_mk2 = new gui.QuenMatKhau.textfield.PasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nhập mật khẩu mới");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Xác nhận lại");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lb_thongBao.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lb_thongBao.setForeground(new java.awt.Color(255, 51, 51));
        lb_thongBao.setText("*");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_Nhan/pharmacy64.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("PharmaHome");

        tf_mk2.setText("passwordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(tf_mk1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(tf_mk2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(lb_thongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_mk1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_mk2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lb_thongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (savePassword()) {
        if (loginForm != null) {
            Notifications.getInstance().show(Notifications.Type.SUCCESS,  "Đổi mật khẩu thành công!!!");
            loginForm.resetLoginForm(); // Reset lại LoginForm
        } else {
            System.out.println("LoginForm chưa được thiết lập!");
            //lb_thongBao.setText("Có lỗi: LoginForm chưa được liên kết.");
            return;
        }

        // Đóng cửa sổ chứa form đổi mật khẩu
        java.awt.Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
    } else {
      //  lb_thongBao.setText("Đổi mật khẩu không thành công!");
    }


    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean KiemTraPassword(String mk, String mk1) {
        if (regax.passwordNV(mk)) {
            if (mk1.equals(mk)) {
                return true;
            }
        } else {
            lb_thongBao.setText("Mật khẩu có ít nhất 6 ký tự, bao gồm ít nhất 1 ký tự chữ và 1 ký tự số");
            return false;
        }
        lb_thongBao.setText("Nhập sai mật khẩu");

        return false;
    }

    public boolean savePassword() {
        String mk = tf_mk1.getText();
        String mk2 = tf_mk2.getText();
        if (!KiemTraPassword(mk, mk2)) {
            return false;
        }
        String pwd = hashpwd.hashPassword(mk2);
        tk_dao.doiMatKHau(tenTK, pwd);
        System.out.println("ten tk" + tenTK + ",mat khau " + pwd);
        return true;
    }

    public interface ResetListener {

        void onReset();
    }

    public void setResetListener(ResetListener listener) {
        this.resetListener = listener;
    }

    private void closeDialog() {
        // Reset lại LoginForm khi DoiMatKhau đóng
        if (loginForm != null) {

            loginForm.resetLoginForm();

        }

        // Đóng JDialog chứa DoiMatKhau
        java.awt.Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof JDialog) {
            ((JDialog) window).dispose();
        }
    }

    public void setLoginForm(LoginForm loginForm) {
        this.loginForm = loginForm;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_thongBao;
    private gui.QuenMatKhau.textfield.TextField tf_mk1;
    private gui.QuenMatKhau.textfield.PasswordField tf_mk2;
    // End of variables declaration//GEN-END:variables
}
