/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.QuenMatKhau;

import connect.ConnectDB;
import dao.NhanVien_DAO;
import dao.OTP_DAO;
import entity.NhanVien;
import java.awt.Window;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import message.Notification;
import utilities.SendEmail;
import gui.LoginForm;
import java.awt.Frame;
import raven.toast.Notifications;

/**
 *
 * @author Lenovo
 */
public class QuenMatKhau_GUI extends javax.swing.JPanel {

    private NhanVien_DAO nv_dao = new NhanVien_DAO();
    private NhanVien nv;
    private Timer timer; // Khai báo Timer
    private int cooldown = 60; // Thời gian chờ (giây)
    private OTP_DAO otp_dao = new OTP_DAO();
    private SendEmail sendEmail = new SendEmail();
    private LoginForm loginForm;
    //  private final LoginForm loginForm;

    /**
     * Creates new form QuenMatKhau_GUI
     */
    public QuenMatKhau_GUI(LoginForm loginForm1) throws SQLException {
//        this.loginForm = new LoginForm();
        loginForm=loginForm1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_XacNhan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_tenTK = new gui.QuenMatKhau.textfield.TextField();
        jLabel1 = new javax.swing.JLabel();
        tf_Email = new gui.QuenMatKhau.textfield.TextField();
        tf_XacNhan = new gui.QuenMatKhau.textfield.TextField();
        lb_Second = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Email");

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nhập mã xác nhận");

        btn_XacNhan.setText("Gửi mã xác nhận");
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Bạn chưa nhận được mã");

        jButton3.setText("Gửi lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("PharmaHome");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_Nhan/pharmacy64.png"))); // NOI18N

        tf_tenTK.setText("NVTRANVietNHan");
        tf_tenTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tenTKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tên tài khoản");

        tf_Email.setText("nhantran.03042021@gmail.com");

        lb_Second.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_Second)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_XacNhan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(13, 13, 13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(tf_tenTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_XacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_tenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lb_Second)
                    .addComponent(jButton3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ten = tf_tenTK.getText();
        if (kiemTraMatKhau(ten)) {

            onXacNhanClick();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        // TODO add your handling code here:
        if (xacNhan()) {
            System.out.println("dung roi");

            startCooldownTimer();

        }

    }//GEN-LAST:event_btn_XacNhanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (xacNhan()) {
            System.out.println("dung roi");

            startCooldownTimer();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf_tenTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tenTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tenTKActionPerformed
    public boolean xacNhan() {
        String maNhanVien = tf_tenTK.getText();
        String email = tf_Email.getText();
        nv = nv_dao.timKiemTheoMa1(maNhanVien);
        System.out.println(nv.getEmail());
        if (nv == null) {
            Notification panel = new Notification(this, Notification.Type.WARNING,
                    Notification.Location.TOP_CENTER, "Nhập sai mã nhân viên hoặc email!!!");
            panel.showNotification();
            return false;
        }

        if (!nv.getEmail().equals(email)) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Nhập sai mã nhân viên hoặc email!!!");
            
            return false;
        }
        if (!nv.isTrangThai()) {
            Notifications.getInstance().show(Notifications.Type.WARNING,  "Nhân viên đã nghĩ viêc!!!");
            
            return false;
        }
        Notifications.getInstance().show(Notifications.Type.SUCCESS, "Mã xác nhận đã được gửi hãy kiểm tra email");
      
        saveOTP(email, maNhanVien);

        return true;
    }

    private void onXacNhanClick() {
        // Kiểm tra logic (ví dụ: nếu mật khẩu đúng)
        boolean isPasswordCorrect = true; // Logic xác minh tại đây

        if (isPasswordCorrect) {
            // Lấy cửa sổ cha của panel này (có thể là JFrame hoặc JDialog)
            Window parentWindow = SwingUtilities.getWindowAncestor(this);

            // Kiểm tra nếu parentWindow là một JDialog
            if (parentWindow instanceof JDialog) {
                JDialog parentDialog = (JDialog) parentWindow;
                parentDialog.dispose(); // Đóng dialog chứa panel này
            } else if (parentWindow instanceof JFrame) {
                // Nếu là JFrame, có thể đóng JFrame hoặc thực hiện hành động khác
                JFrame parentFrame = (JFrame) parentWindow;
                parentFrame.dispose(); // Đóng JFrame nếu cần
            }

            // Gửi tín hiệu mở panel mới
            openNextPanel();
        } else {
            JOptionPane.showMessageDialog(this, "Mật khẩu sai. Vui lòng thử lại!");
        }
    }

    private void openNextPanel() {
        // Giả sử bạn muốn mở một JFrame chứa panel mới
        String ten = tf_tenTK.getText();
        DoiMatKhau doiMatKhau = new DoiMatKhau(ten,loginForm);

        doiMatKhau.setLoginForm(loginForm); // Truyền LoginForm hiện tại vào

        // Truyền LoginForm hiện tại vào DoiMatKhau
        doiMatKhau.setLoginForm(loginForm); // loginForm là tham chiếu tới LoginForm hiện tại

        // Hiển thị dialog
        JDialog dialog = new JDialog((Frame) null, "Đổi Mật Khẩu", true);
        dialog.getContentPane().add(doiMatKhau);
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }

    private void startCooldownTimer() {
        btn_XacNhan.setEnabled(false); // Vô hiệu hóa nút "Gửi mã xác nhận"
        jButton3.setEnabled(false); // Vô hiệu hóa nút "Gửi lại"

        cooldown = 60; // Đặt lại thời gian đếm ngược
        timer = new Timer(1000, e -> {
            cooldown--;
            if (cooldown <= 0) {
                timer.stop();
                btn_XacNhan.setEnabled(true); // Kích hoạt lại nút sau khi hết thời gian chờ
                jButton3.setEnabled(true);
            } else {
                lb_Second.setText(cooldown+"s");
                System.out.println("Còn " + cooldown + " giây.");
            }
        });
        timer.start(); // Bắt đầu đếm ngược
    }

    public String saveOTP(String email, String maXacNhan) {
        String otp = sendEmail.generateOTP();
        sendEmail.sendOtpEmail(email, otp);
        otp_dao.saveOtpToDatabase(maXacNhan.trim(), otp);
        System.out.println(otp + "  " + maXacNhan);
        otp_dao.deleteOTP60s();
        return otp;
    }

    public boolean kiemTraMatKhau(String tenTaiKhoan) {
        try {
        
        String xacNhan = tf_XacNhan.getText();
        String otp = otp_dao.getMaXacNhan(tenTaiKhoan);
        if (otp.equals(xacNhan)) {

            return true;
        }
        System.out.println(xacNhan + "  " + otp);
            Notifications.getInstance().show(Notifications.Type.WARNING,  "Nhập sai mã xác nhân!!!");
        } catch (Exception e) {
            Notifications.getInstance().show(Notifications.Type.WARNING,  "Bạn chưa nhập sai mã xác nhân!!!");
        }
        return false;
    }

    public String getMaNV() {
        return tf_Email.getText();
    }

//    public static void main(String[] args) throws SQLException {
//        JFrame frame = new JFrame("Thong Ke Thuoc");
//        ConnectDB.connect();
//        frame.setSize(800, 600);
//        frame.add(new QuenMatKhau_GUI(loginForm));
//        frame.setVisible(true);
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_Second;
    private gui.QuenMatKhau.textfield.TextField tf_Email;
    private gui.QuenMatKhau.textfield.TextField tf_XacNhan;
    private gui.QuenMatKhau.textfield.TextField tf_tenTK;
    // End of variables declaration//GEN-END:variables
}
